version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'ssl=off']

volumes:
  postgres_data:
